### ISSUE TITLE
How to add a auth protected url 

### ISSUE THREAD

**Issue by AMJADMISTEO** [GeoTIFF/geoblaze#184]
When trying to add a geotiff layer from an api that is auth protected cannot able to pass autharization headers

**Comment by DanielJDufour** [comment]
Hi, sorry for the late reply.  This is a really good question without a good answer.  Here's some options:
1) Load the whole file:
```js
const arrayBuffer = await fetch(url, { headers }).then(res => res.arrayBuffer());
const georaster = await geoblaze.parse(arrayBuffer);
```

2) Create an proxy url that uses an access token in the url.  Instead of passing the authorization in your headers each time.  Authorize once, receiving and access token and then use that.
```js
const { accessToken } = fetch(authorization_url, { headers }).then(res => res.json());
const georaster = await geoblaze.parse(url + "?access_token=" + access_token);
```

3) Fork georaster and [geotiff.js](https://github.com/geotiffjs/geotiff.js).  It would be great it users could pass in a custom fetch function that would be used by georaster and its dependency geotiff.js.  We could then intercept the requesets and conditionally add headers.  However, I'm not sure the thinking of the maintainer of geotiff.js on this question.  You could ask him here: https://github.com/geotiffjs/geotiff.js/issues

Lastly, if you happen to be using AWS S3 or a similar service, you might be able to get a "signed url" in which case you can use that signed url without headers.
